# frozen_string_literal: true

module EventMappingEngine
  module EventIds
    INCOMING_FEES = 73
    HACK_CLUB_BANK = 74
    NOEVENT = 72
    HACKATHON_GRANT_FUND = 1610
    WINTER_HARDWARE_WONDERLAND_GRANT_FUND = 1966
    ARGOSY_GRANT_FUND = 3349
    FIRST_TRANSPARENCY_GRANT_FUND = 1803
    HACK_FOUNDATION_INTEREST = 71
    REIMBURSEMENT_CLEARING = 69
    SVB_SWEEPS = 70
  end
end
